foo:
  bar: baz
  qux: quux
corge:
  grault:
    garply: waldo
fred:
  - xyzzy
  - plugh
  - thud
one:
  - two: three
  - four: five
some-thing:
  another: thing
verbatim-upper:
  verbatim-prop:
    value:
      - foobar:
          qux: quux
    verbatim: false
